version: "3.8"
services:
  app:
    container_name: toddler-world-dev
    image: toddler-world-dev
    build:
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"